[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ipxe"
version = "0.1.0"
description = "Automated iPXE network boot menu"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "elfshoe",
]
